# Site settings
title: Obituaries by Molly Ivins
description: "Links and citations for obituaries written by the late Molly Ivins."
baseurl: "www.ivinsobits.com"
url: "https://ivinsobits.com/"
tagline: "A tribute to her tributes"

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
